services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_RECOMMENDATION_API_URL=http://localhost:8000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    networks:
      - openlearn-network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@postgres:5432/openlearn}
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - openlearn-network
    restart: unless-stopped

  recommendation-api:
    build:
      context: ./apps/recommendation-api
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
    volumes:
      - ./apps/recommendation-api:/app
    networks:
      - openlearn-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-openlearn}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - openlearn-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - openlearn-network
    restart: unless-stopped

networks:
  openlearn-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
